# Generated by Django 5.2.16 on 2026-07-14 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_user_failed_pin_attempts_user_pin_locked_until"),
        ("opd", "0004_consultationnote"),
        ("patients", "0003_patientdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("collected", "Sample collected"),
                            ("reported", "Reported"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ordered",
                        max_length=12,
                    ),
                ),
                ("indication", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="accounts.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders",
                        to="opd.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                ("short_code", models.CharField(blank=True, max_length=24)),
                ("category", models.CharField(blank=True, max_length=80)),
                (
                    "sample_type",
                    models.CharField(
                        blank=True, help_text="blood, urine, ...", max_length=60
                    ),
                ),
                ("default_unit", models.CharField(blank=True, max_length=40)),
                ("reference_range", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="lab_labtest_name_b73df5_idx"),
                    models.Index(
                        fields=["short_code"], name="lab_labtest_short_c_165943_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LabOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_text", models.CharField(max_length=160)),
                ("result_value", models.CharField(blank=True, max_length=120)),
                ("result_unit", models.CharField(blank=True, max_length=40)),
                ("reference_range", models.CharField(blank=True, max_length=80)),
                (
                    "flag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("low", "Low"),
                            ("abnormal", "Abnormal"),
                        ],
                        max_length=12,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lab.laborder",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lab.labtest",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["patient", "-created_at"], name="lab_laborde_patient_6c9a6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["status"], name="lab_laborde_status_ad1ac5_idx"),
        ),
    ]
