# Generated by Django 5.2.16 on 2026-07-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_pin_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="pin_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
