# Generated by Django 5.2.16 on 2026-09-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_failed_pin_attempts_user_pin_locked_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="accepts_online_booking",
            field=models.BooleanField(
                default=False,
                help_text="Let patients book this doctor's OPD slots from the website.",
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="public_bio",
            field=models.TextField(
                blank=True, help_text="Short paragraph shown on the public website."
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="show_on_website",
            field=models.BooleanField(
                default=False,
                help_text="List this doctor on the public hospital website.",
                verbose_name="Show on public website",
            ),
        ),
    ]
