# Generated by Django 5.2.16 on 2026-07-26 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opd", "0005_teleconsult"),
        ("patients", "0003_patientdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "call_sid",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("from_number", models.CharField(blank=True, max_length=32)),
                ("to_number", models.CharField(blank=True, max_length=32)),
                ("language", models.CharField(default="en-IN", max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("no_agent", "Agent unavailable"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("messages", models.JSONField(blank=True, default=list)),
                ("turns", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booked_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_calls",
                        to="opd.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_calls",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
