# Generated by Django 5.2.15 on 2026-07-02 18:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0002_patient_is_unknown_patient_privacy_notice_deferred_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('token_number', models.PositiveSmallIntegerField()),
                ('token_label', models.CharField(max_length=12)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('appointment', 'Appointment')], default='walk_in', max_length=16)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('vitals_done', 'Vitals done'), ('in_consult', 'In consult'), ('on_hold', 'On hold'), ('parked', 'Parked'), ('completed', 'Completed'), ('no_show', 'No show')], db_index=True, default='waiting', max_length=16)),
                ('is_emergency', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('skip_count', models.PositiveSmallIntegerField(default=0)),
                ('is_mlc', models.BooleanField(default=False, verbose_name='Medico-legal case')),
                ('mlc_brought_by', models.CharField(blank=True, max_length=180)),
                ('mlc_police_station', models.CharField(blank=True, max_length=180)),
                ('mlc_notes', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, choices=[('home', 'Home'), ('follow_up', 'Follow-up'), ('admit_advised', 'Admission advised'), ('referred', 'Referred out'), ('expired', 'Expired')], max_length=16)),
                ('disposition_note', models.CharField(blank=True, max_length=240)),
                ('followup_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('referred_to', models.CharField(blank=True, max_length=180)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('vitals_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('consult_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], default='cash', max_length=8)),
                ('is_refunded', models.BooleanField(default=False)),
                ('refund_reason', models.CharField(blank=True, max_length=240)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_created', to=settings.AUTH_USER_MODEL)),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_refunded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='opd.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('slot_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked in'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], default='booked', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('cancelled_reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='opd.visit')),
            ],
            options={
                'ordering': ['date', 'slot_time'],
            },
        ),
        migrations.CreateModel(
            name='VitalsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('300'))])),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30')), django.core.validators.MaxValueValidator(Decimal('250'))])),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(100)], verbose_name='SpO2 %')),
                ('temp_f', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('90')), django.core.validators.MaxValueValidator(Decimal('110'))], verbose_name='Temperature °F')),
                ('rbs', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(900)], verbose_name='RBS mg/dL')),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('lmp_date', models.DateField(blank=True, null=True, verbose_name='LMP')),
                ('chief_complaint', models.CharField(blank=True, max_length=240)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_recorded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='opd.visit')),
            ],
            options={
                'verbose_name_plural': 'vitals records',
            },
        ),
        migrations.CreateModel(
            name='TokenSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_sequences', to='accounts.doctorprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'date'), name='uniq_token_seq_doctor_date')],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_date', 'status'], name='opd_visit_visit_d_3d4195_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('doctor', 'visit_date', 'token_number'), name='uniq_token_doctor_date'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'date'], name='opd_appoint_doctor__b7ef35_idx'),
        ),
    ]
