# Generated by Django 5.2.16 on 2026-07-09 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_failed_pin_attempts_user_pin_locked_until"),
        ("opd", "0001_initial"),
        (
            "patients",
            "0002_patient_is_unknown_patient_privacy_notice_deferred_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "in_consult")),
                fields=("doctor", "visit_date"),
                name="uniq_one_in_consult_per_doctor_day",
            ),
        ),
    ]
