# Generated by Django 5.2.16 on 2026-07-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opd", "0002_visit_uniq_one_in_consult_per_doctor_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="followup_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
