# Generated by Django 5.2.16 on 2026-07-14 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opd", "0003_visit_followup_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chief_complaint", models.CharField(blank=True, max_length=240)),
                (
                    "history",
                    models.TextField(
                        blank=True, verbose_name="History of present illness"
                    ),
                ),
                (
                    "examination",
                    models.TextField(blank=True, verbose_name="Examination / findings"),
                ),
                ("diagnosis", models.CharField(blank=True, max_length=240)),
                ("assessment", models.TextField(blank=True)),
                ("plan", models.TextField(blank=True, verbose_name="Plan / treatment")),
                ("advice", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note",
                        to="opd.visit",
                    ),
                ),
            ],
        ),
    ]
