# Generated by Django 5.2.16 on 2026-07-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="reference",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="scheduled_for",
            field=models.DateField(blank=True, null=True),
        ),
    ]
