# Generated by Django 5.2.16 on 2026-09-03 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True)),
                (
                    "starts_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "ends_on",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank to show until manually deactivated.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-starts_on"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "name_marathi",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Name (Marathi)"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional emoji shown on the service card.",
                        max_length=8,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PublicBookingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("mobile", models.CharField(blank=True, max_length=10)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("rate_limited", "Rate limited"),
                            ("rejected", "Rejected"),
                            ("spam", "Spam (honeypot)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="publicsite__ip_addr_adb940_idx",
                    ),
                    models.Index(
                        fields=["mobile", "created_at"],
                        name="publicsite__mobile_94e623_idx",
                    ),
                ],
            },
        ),
    ]
