# Generated by Django 5.2.16 on 2026-07-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HospitalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Dr. Manavatkar Hospital", max_length=180),
                ),
                (
                    "name_marathi",
                    models.CharField(
                        blank=True,
                        default="डॉ. मानवतकर हॉस्पिटल",
                        max_length=180,
                        verbose_name="Name (Marathi)",
                    ),
                ),
                (
                    "address_line",
                    models.CharField(
                        blank=True,
                        default='"Dattadham", Jamner Road, Bhusawal',
                        max_length=240,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="(02582) 240520", max_length=60
                    ),
                ),
                (
                    "slip_footer",
                    models.CharField(
                        blank=True,
                        default="कृपया आपल्या टोकन क्रमांकाची वाट पहा · Please wait for your token number",
                        max_length=240,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "hospital profile",
                "verbose_name_plural": "hospital profile",
            },
        ),
    ]
