# Generated by Django 5.2.16 on 2026-09-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalprofile",
            name="about_text",
            field=models.TextField(
                blank=True,
                help_text="A few sentences about the hospital, shown on the website.",
            ),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="city",
            field=models.CharField(blank=True, default="Bhusawal", max_length=80),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="emergency_phone",
            field=models.CharField(
                blank=True,
                help_text="Casualty / 24-hour number, shown prominently.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="map_query",
            field=models.CharField(
                blank=True,
                help_text="Address or 'lat,lng' used for the Directions link on the website.",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="opd_hours_text",
            field=models.CharField(
                blank=True,
                default="Mon–Sat 10:00–13:00 and 17:00–20:00 · Sunday closed",
                help_text="Human-readable OPD timings for the website and footer.",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="public_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="state",
            field=models.CharField(blank=True, default="Maharashtra", max_length=80),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="tagline",
            field=models.CharField(
                blank=True,
                default="Caring for Bhusawal families since 1985",
                help_text="One line under the hospital name on the website home page.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="website_domain",
            field=models.CharField(
                blank=True,
                default="manwatkarhospital.in",
                help_text="Canonical public domain, used in page metadata.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="hospitalprofile",
            name="name",
            field=models.CharField(default="Manwatkar Hospital", max_length=180),
        ),
        migrations.AlterField(
            model_name="hospitalprofile",
            name="name_marathi",
            field=models.CharField(
                blank=True,
                default="मानवतकर हॉस्पिटल",
                max_length=180,
                verbose_name="Name (Marathi)",
            ),
        ),
    ]
