# Generated by Django 5.2.16 on 2026-09-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_hospitalprofile_about_text_hospitalprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalprofile",
            name="opd_hours_text",
            field=models.CharField(
                blank=True,
                default="Mon–Sat 10:00–13:00 and 17:00–20:00 · Tuesday evening closed",
                help_text="Human-readable OPD timings for the website and footer.",
                max_length=240,
            ),
        ),
        migrations.AlterField(
            model_name="hospitalprofile",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="One line under the hospital name on the website home page.",
                max_length=200,
            ),
        ),
    ]
