# Generated by Django 5.2.16 on 2026-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_drop_invented_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalprofile",
            name="opd_hours_text",
            field=models.CharField(
                blank=True,
                default="Open daily 10:00–13:00 and 17:00–20:00 · Tuesday evening closed",
                help_text="Human-readable OPD timings for the website and footer.",
                max_length=240,
            ),
        ),
    ]
