# Generated by Django 5.2.16 on 2026-07-14 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_user_failed_pin_attempts_user_pin_locked_until"),
        ("opd", "0003_visit_followup_date"),
        (
            "patients",
            "0002_patient_is_unknown_patient_privacy_notice_deferred_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(help_text="INN / generic name", max_length=180),
                ),
                ("brand_name", models.CharField(blank=True, max_length=180)),
                (
                    "strength",
                    models.CharField(
                        blank=True, help_text="e.g. 500 mg", max_length=60
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        blank=True, help_text="tablet, syrup, ...", max_length=60
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("otc", "OTC / general"),
                            ("h", "Schedule H"),
                            ("h1", "Schedule H1"),
                            ("x", "Schedule X"),
                        ],
                        default="otc",
                        max_length=8,
                    ),
                ),
                (
                    "ingredients",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated actives, for allergy/duplicate checks",
                        max_length=240,
                    ),
                ),
                (
                    "default_sig",
                    models.CharField(
                        blank=True, help_text="Default dosage signature", max_length=120
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["generic_name", "brand_name"],
                "indexes": [
                    models.Index(
                        fields=["generic_name"], name="prescriptio_generic_a1e7d2_idx"
                    ),
                    models.Index(
                        fields=["brand_name"], name="prescriptio_brand_n_cee123_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("generic_name", "brand_name", "strength", "form"),
                        name="uniq_drug_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diagnosis", models.CharField(blank=True, max_length=240)),
                ("advice", models.TextField(blank=True)),
                (
                    "followup_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("revised", "Revised (superseded)"),
                        ],
                        default="issued",
                        max_length=8,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "allergy_override_reason",
                    models.CharField(blank=True, max_length=240),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="accounts.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="prescriptions.prescription",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="opd.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_text", models.CharField(max_length=240)),
                (
                    "dosage",
                    models.CharField(
                        blank=True, help_text="e.g. 1-0-1 or BD", max_length=60
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("quantity", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("instructions", models.CharField(blank=True, max_length=180)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "drug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prescriptions.drug",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "-created_at"], name="prescriptio_patient_d016dc_idx"
            ),
        ),
    ]
