# Generated by Django 5.2.15 on 2026-07-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_unknown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='privacy_notice_deferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='privacy_notice_deferred_reason',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
