# Generated by Django 5.2.16 on 2026-07-14 21:39

import apps.patients.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opd", "0004_consultationnote"),
        (
            "patients",
            "0002_patient_is_unknown_patient_privacy_notice_deferred_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.patients.models.document_upload_path
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("lab", "Lab report"),
                            ("prescription", "Prescription scan"),
                            ("imaging", "Scan / imaging"),
                            ("discharge", "Discharge / summary"),
                            ("other", "Other"),
                        ],
                        default="lab",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=180)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="opd.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
