# Generated by Django 5.2.16 on 2026-07-15 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("is_paid", models.BooleanField(default=True)),
                ("default_days", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("grace_minutes", models.PositiveSmallIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="ShiftInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Roster date the shift belongs to"
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("leave", "On leave"),
                            ("off", "Off / holiday"),
                        ],
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                (
                    "is_on_duty",
                    models.BooleanField(
                        default=False, help_text="Called in off-roster"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="attendance.shift",
                    ),
                ),
            ],
            options={
                "ordering": ["window_start"],
            },
        ),
        migrations.CreateModel(
            name="RegularizationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regularizations_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regularizations_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regularizations",
                        to="attendance.shiftinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_in", models.DateTimeField(blank=True, null=True)),
                ("last_out", models.DateTimeField(blank=True, null=True)),
                ("punch_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                        ],
                        default="absent",
                        max_length=12,
                    ),
                ),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("derived_at", models.DateTimeField(auto_now=True)),
                (
                    "shift_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="attendance.shiftinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=120)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("is_punch_exempt", models.BooleanField(default=False)),
                ("joined_on", models.DateField(blank=True, null=True)),
                ("exited_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name", "user__username"],
            },
        ),
        migrations.CreateModel(
            name="ShiftSwapRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="swaps_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests",
                        to="attendance.shiftinstance",
                    ),
                ),
                (
                    "to_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_offers",
                        to="attendance.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shiftinstance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_instances",
                to="attendance.staffprofile",
            ),
        ),
        migrations.CreateModel(
            name="PunchEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_time", models.DateTimeField(db_index=True)),
                (
                    "device_time",
                    models.DateTimeField(
                        blank=True, help_text="Kiosk clock at capture", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("face", "Face"),
                            ("pin", "PIN"),
                            ("manual", "Manual (admin)"),
                            ("back_entry", "Back-dated entry"),
                        ],
                        default="face",
                        max_length=12,
                    ),
                ),
                ("device", models.CharField(blank=True, max_length=64)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="punch_photos/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punches",
                        to="attendance.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_time"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leaves_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attendance.leavetype",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="attendance.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FaceEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("embedding", models.JSONField(help_text="512-d ArcFace vector")),
                (
                    "reference_photo",
                    models.FileField(blank=True, null=True, upload_to="face_refs/"),
                ),
                ("quality", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="attendance.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consent_given", models.BooleanField(default=False)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("biometric", "Biometric (face)"),
                            ("pin", "PIN only"),
                        ],
                        default="pin",
                        max_length=12,
                    ),
                ),
                ("notice_version", models.CharField(blank=True, max_length=64)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="attendance.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shiftinstance",
            index=models.Index(
                fields=["date", "status"], name="attendance__date_4c534a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftinstance",
            constraint=models.UniqueConstraint(
                fields=("staff", "shift", "date"), name="uniq_shift_instance"
            ),
        ),
        migrations.AddIndex(
            model_name="punchevent",
            index=models.Index(
                fields=["staff", "event_time"], name="attendance__staff_i_77572d_idx"
            ),
        ),
    ]
